spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=pwd
twins-notify.concurrency=3

grpc.server.port=6565

twins.introspection.url=http://localhost:8080/private/auth/introspect/v1
twins.notification.status.update.url=http://localhost:8080/private/domain/user/subscription/v1


spring.datasource.url=jdbc:postgresql://localhost:5432/twinhorn
spring.datasource.username=usr
spring.datasource.password=pwd
